export let cvItems = [
  {
    category: 'job',
    id: 1,
    image: 'img/logo-kamado.webp',
    name: 'KamadoB10 Germany',
    role: 'Web and Graphic Designer',
    location: 'Ebersbach, DE',
    fromYear: '2020',
    fromMonth: '08',
    toYear: '2022',
    toMonth: '04',
    shortdescription: 'Webdesign, Printing Materials, Marketing, Manufactoring',
    info: 'I worked as a Web and Graphic Designer. As this was a Start-Up company, i was also involved in the manufacturing process. I learned about the inner workings of the company and was therefore also able to focus on the key aspects of the company in the marketing materials.'
  },
  {
    category: 'job',
    id: 2,
    image: 'img/ditf-logo-weis.svg',
    name: 'DITF',
    role: 'Research Assistant',
    location: 'Denkendorf, DE',
    fromYear: '2017',
    fromMonth: '08',
    toYear: '2020',
    toMonth: '08',
    shortdescription: 'Laboratory work, preparation of samples, MS Office use',
    info: 'In this Institute i worked as a Research Assistant. I learned a lot about the research process and the importance of attention to detail. I also gained experience in conducting experiments and collecting and analyzing data. I also learned the importance of being organized and keeping accurate records of my work.'
  },
  {
    category: 'job',
    id: 3,
    image: 'img/logo-letratec.png',
    name: 'Letratec',
    role: 'Intern',
    location: 'Buenos Aires, AR',
    fromYear: '2015',
    fromMonth: '11',
    toYear: '2015',
    toMonth: '12',
    shortdescription: 'Design process of signage, selection of materials',
    info: 'In this internship i learned about the process of designing and creating signage for businesses. I also learned about the different materials and manufacturing processes used to create signs, and how to work with clients to understand their needs and create effective signage solutions.'
  },
  {
    category: 'education',
    id: 1,
    image: 'img/logo_UPV_principal.svg',
    name: 'M. Eng. in Design Engineering',
    role: 'Universitat Politécnica de Valencia',
    location: 'Valencia, ES',
    fromYear: '2021',
    fromMonth: '09',
    toYear: '2023',
    toMonth: '06',
    shortdescription: 'Principles of Design Engineering, Typography, Color Theory, Visual communication',
    info: 'Universiat Politécnica de Valencia. I learned about the principles and practices of Design Engineering. I studied topics such as typography, color theory, and visual communication, as well as more technical subjects such as design software and printing processes.'
  },
  {
    category: 'education',
    id: 2,
    image: 'img/logo-uni-stuttgart.svg',
    name: 'B. Sc. in Materials Science',
    role: 'University of Stuttgart',
    location: 'Stuttgart, DE',
    fromYear: '2016',
    fromMonth: '10',
    toYear: '2020',
    toMonth: '09',
    shortdescription: 'Fundamentals of Materials Science, Material properties and behavior, metals, plastics, ceramics',
    info: 'University of Stuttgart. As a materials science major, I learned about the properties and behavior of different materials, such as metals, ceramics, and polymers. Additionally, I gained experience in conducting experiments and analyzing data to better understand the behavior of materials.'
  },
  {
    category: 'education',
    id: 3,
    image: 'img/logo_gympl.jpg',
    name: 'High School Graduation',
    role: 'Gymnasium Plochingen',
    location: 'Plochingen, DE',
    fromYear: '2007',
    fromMonth: '11',
    toYear: '2015',
    toMonth: '07',
    shortdescription: 'Highest degree of general education in Germany, favorite subjects were math, physics and art',
    info: 'Gymnasium Plochingen. In High school, my favorite subjects were math, physics and art. I always liked logic and wanted to figure out how things work, while trying to live out my creative side.'
  }
];