export let cvItems = [
  {
    category: 'job',
    id: 1,
    image: 'cv_items/logo-kamado.webp',
    imageDark: '',
    name: 'KamadoB10 Germany',
    role: 'Web and Graphic Designer',
    location: 'Ebersbach, DE',
    fromYear: '2020',
    fromMonth: '08',
    toYear: '2022',
    toMonth: '04',
    shortdescription: 'Web design, printing materials, marketing, manufacturing',
    info: 'I worked as a Web and Graphic Designer. As this was a Start-Up company, i was also involved in the manufacturing process. I learned about the inner workings of the company and was therefore also able to focus on the key aspects of the company in the marketing materials.'
  },
  {
    category: 'job',
    id: 2,
    image: 'cv_items/logo-ditf-weiss.svg',
    imageDark: 'cv_items/logo-ditf-weiss.svg',
    name: 'DITF',
    role: 'Research Assistant',
    location: 'Denkendorf, DE',
    fromYear: '2017',
    fromMonth: '08',
    toYear: '2020',
    toMonth: '08',
    shortdescription: 'Laboratory work, preparation of samples, MS office use',
    info: 'In this institute i worked as a research assistant. I learned a lot about the research process and the importance of attention to detail. I also gained experience in conducting experiments and collecting and analyzing data. I also learned the importance of being organized and keeping accurate records of my work.'
  },
  {
    category: 'job',
    id: 3,
    image: 'cv_items/logo-letratec.webp',
    imageDark: '',
    name: 'Letratec',
    role: 'Intern',
    location: 'Buenos Aires, AR',
    fromYear: '2015',
    fromMonth: '11',
    toYear: '2015',
    toMonth: '12',
    shortdescription: 'Design process of signage, selection of materials',
    info: 'In this internship i learned about the process of designing and creating signage for businesses. I also learned about the different materials and manufacturing processes used to create signs, and how to work with clients to understand their needs and create effective signage solutions.'
  },
  {
    category: 'education',
    id: 1,
    image: 'cv_items/logo-upv.svg',
    imageDark: '',
    name: 'M. Eng. in Design Engineering',
    role: 'Universitat Politécnica de Valencia',
    location: 'Valencia, ES',
    fromYear: '2021',
    fromMonth: '09',
    toYear: '2023',
    toMonth: '07',
    shortdescription: 'Principles of design engineering, typography, color theory, visual communication',
    info: 'Universiat Politécnica de Valencia. I learned about the principles and practices of Design Engineering. I studied topics such as typography, color theory, and visual communication, as well as more technical subjects such as design software and printing processes.'
  },
  {
    category: 'education',
    id: 2,
    image: 'cv_items/logo-uni-stuttgart.svg',
    imageDark: '',
    name: 'B. Sc. in Materials Science',
    role: 'University of Stuttgart',
    location: 'Stuttgart, GER',
    fromYear: '2016',
    fromMonth: '10',
    toYear: '2020',
    toMonth: '09',
    shortdescription: 'Fundamentals of materials science, material properties and behavior, metals, plastics, ceramics',
    info: 'University of Stuttgart. As a materials science major, I learned about the properties and behavior of different materials, such as metals, ceramics, and polymers. Additionally, I gained experience in conducting experiments and analyzing data to better understand the behavior of materials.'
  },
  {
    category: 'education',
    id: 3,
    image: 'cv_items/logo-gympl.webp',
    imageDark: '',
    name: 'High School Graduation',
    role: 'Gymnasium Plochingen',
    location: 'Plochingen, GER',
    fromYear: '2007',
    fromMonth: '11',
    toYear: '2015',
    toMonth: '07',
    shortdescription: 'Highest degree of general education in Germany, favorite subjects were math, physics and art',
    info: 'Gymnasium Plochingen. In high school, my favorite subjects were math, physics and art. I always liked logic and wanted to figure out how things work, while trying to live out my creative side.'
  },
  {
    category: 'certificate',
    id: 1,
    link: '/works#graphicdesign-trels',
    image: 'cv_items/certificate-tau-censored.webp',
    name: 'III Concurso de Diseño De Una Pieza Cerámica',
    fromYear: '10/02/2022',
    shortdescription: 'TAU Cerámica: I achieved second place in the graphic design contest. The objective was to design a ceramic tile, fitting to the famous Estacion Norte in Valencia.',
    info: 'See Project',
  },
  {
    category: 'certificate',
    id: 2,
    link: 'https://www.futurelearn.com/profiles/19981862',
    image: 'cv_items/certificate-designing-for-a-sustainable-future.webp',
    name: 'Designing for a sustainable Future',
    fromYear: '21/02/2023',
    shortdescription: "The online course explored design thinking applied to sustainability. It covered topics from AI to rewilding, emphasizing empathy, technology's problem-solving potential, and innovative solutions to the climate crisis.",
    info: 'See Certificate',
  },
  {
    category: 'certificate',
    id: 3,
    link: 'https://static.semrush.com/academy/certificates/3d9e1fe2f3/sebastian-jans_2.pdf',
    image: 'cv_items/certificate-seo-crash-course.webp',
    name: 'SEO Crash Course',
    fromYear: '22/02/2023',
    shortdescription: "A crash course about SEO, teaching me the value of keywords and the importance of finding your right target audience.",
    info: 'See Certificate',
  },
  {
    category: 'certificate',
    id: 4,
    link: 'https://www.linkedin.com/learning/certificates/c6873bdf46d353871733e92e89b0db4d0631d2dc7f7fd2689fb62006c4985bfc?trk=share_certificate',
    image: 'cv_items/certificate-ux-1.webp',
    name: 'UX Design: 1 Overview',
    fromYear: '18/07/2023',
    shortdescription: "A course about User Experience, where i was able to deepen my knowledge about the importance of UX and how to create a good user experience.",
    info: 'See Certificate',
  },
  {
    category: 'certificate',
    id: 5,
    link: 'https://www.linkedin.com/learning/certificates/214fc26fd55146d90e74b44a0848dca7aa27108a3ba38e76d090d572f97a741f?trk=share_certificate',
    image: 'cv_items/certificate-ux-2.webp',
    name: 'UX Design: 2 Analyzing User Data',
    fromYear: '18/07/2023',
    shortdescription: "A course about User Experience, where i learned how to collect and analyze user data.",
    info: 'See Certificate',
  },
];